// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import tema1reloaded.Grupa;
import tema1reloaded.Persoana;

/************************************************************/
/**
 * 
 */
public class Director extends Persoana {
	/**
	 * 
	 */
	private Grupa[] grupe;

	/**
	 * 
	 * @param numeGrupa 
	 */
	public void getGrupa(String numeGrupa) {
	}

	/**
	 * 
	 */
	public void topAbsente() {
	}

	/**
	 * 
	 */
	public void topEleviNote() {
	}

	/**
	 * 
	 */
	public void getNume() {
	}

	/**
	 * 
	 */
	public void getCNP() {
	}

	/**
	 * 
	 */
	public void getTelefon() {
	}
};
