// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import tema1reloaded.Grupa;
import tema1reloaded.Materie;
import tema1reloaded.Parinte;
import tema1reloaded.Persoana;

/************************************************************/
/**
 * 
 */
public class Elev extends Persoana {
	/**
	 * 
	 */
	private Grupa grupa;
	/**
	 * 
	 */
	private int[] absente;
	/**
	 * 
	 */
	private Parinte parinte;
	
	/**
	 * 
	 */
	public void getNoteElev() {
	}

	/**
	 * 
	 * @param materie 
	 */
	public void motivareAbsenta(Materie materie) {
	}

	/**
	 * 
	 */
	public void afisareElev() {
	}

	/**
	 * 
	 */
	public void getAbsente() {
	}

	/**
	 * 
	 */
	public void getGrupa() {
	}

	/**
	 * 
	 */
	public void getNume() {
	}

	/**
	 * 
	 */
	public void getCNP() {
	}

	/**
	 * 
	 */
	public void getTelefon() {
	}

	/**
	 * 
	 */
	public void getParinte() {
	}

	/**
	 * 
	 */
	public void afisareNote() {
	}
};
