// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Grupa {

	private String numeGrupa;
	private ArrayList<Elev> eleviInscrisi = new ArrayList<Elev>();
	private HashMap<String, HashMap <Materie, ArrayList<Integer>>> catalog = new HashMap<>();
	private HashMap<String, Integer> absente = new HashMap<>();
	
	public Grupa(String numeGrupa) {
		this.numeGrupa = numeGrupa;
	}

	
	public void adaugareElev(Elev elev) {
		
		if(!this.existaElev(elev.nume)) {
			eleviInscrisi.add(elev);
			absente.put(elev.nume, 0);
		}
		
		if(!catalog.containsKey(elev.nume)) {
			HashMap <Materie, ArrayList<Integer>> subiecteDeStudiu = new HashMap<>();
			for (Materie materie : Materie.values()) { 
			    ArrayList<Integer> noteMaterie = new ArrayList<>();
			    subiecteDeStudiu.put(materie, noteMaterie);
			}
			catalog.put(elev.nume, subiecteDeStudiu);
		}
		
	}

	private void stergereElev(Elev elev) {
		if(!eleviInscrisi.isEmpty()) {
			if(eleviInscrisi.contains(elev)) {
				eleviInscrisi.remove(elev);
				catalog.remove(elev.nume);
				absente.remove(elev.nume);
			}
			else
				System.out.println("Grupa nu contine acest elev");
		}
		else
			System.out.println("Nu exista inca elevi in aceasta grupa");
	}


	public void afisareGrupa() {
		for(Elev elev : eleviInscrisi)
			System.out.println(elev.nume);
	}

	//use try-catch block
	public Elev getElev(String nume) {
		
		for(Elev elev : eleviInscrisi) {
			if(nume.equals(elev.nume))
				return elev;
		}
		
		System.out.println("Elevul nu exista");
		return null;
			
	}


	public void getNote(String nume, String numeMaterie) {
		if(catalog.containsKey(nume)) {
			Materie materie = Materie.valueOf(numeMaterie);
			System.out.println(catalog.get(nume).get(materie).toString());
		}
	}

	/**
	 * 
	 */
	public int getAbsente(String nume) {
		return absente.get(nume);
	}

	/**
	 * 
	 * @param elev 
	 * @param numeMaterie 
	 * @param nota 
	 * @return 
	 */
	public void adaugareNota(String nume, String numeMaterie, int nota) {
		Materie materie = Materie.valueOf(numeMaterie);
		catalog.get(nume).get(materie).add(nota);
	}


	public void adaugareAbsenta(String nume) {
		absente.put(nume, absente.get(nume) + 1);
	}

	/**
	 * 
	 * @param numeElev 
	 * @return 
	 */
	public boolean existaElev(String numeElev) {
		for(int i=0; i<eleviInscrisi.size(); i++)
			if(eleviInscrisi.get(i).nume.equals(numeElev))
				return true;
		return false;
	}

	/**
	 * 
	 */
	public void topAbsente() {
	}

	/**
	 * 
	 */
	public void topEleviNote() {
		
	}
};
