// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import tema1reloaded.Elev;

/************************************************************/
/**
 * 
 */
public class Grupa {
	/**
	 * 
	 */
	private String numeGrupa;
	/**
	 * 
	 */
	private Elev[] eleviInscrisi;
	/**
	 * 
	 */
	private undefined catalog;
	/**
	 * 
	 */
	private int[] absente;

	/**
	 * 
	 * @param elev 
	 */
	public void adaugareElev(Elev elev) {
	}

	/**
	 * 
	 * @param elev 
	 */
	private void stergereElev(Elev elev) {
	}

	/**
	 * 
	 */
	public void afisareGrupa() {
	}

	/**
	 * 
	 * @param cnpElev 
	 */
	public void getElev(String cnpElev) {
	}

	/**
	 * 
	 * @param materie 
	 */
	public void getNote(String materie) {
	}

	/**
	 * 
	 */
	public void getAbsente() {
	}

	/**
	 * 
	 * @param elev 
	 * @param numeMaterie 
	 * @param nota 
	 * @return 
	 */
	public short adaugareNota(Elev elev, String numeMaterie, short nota) {
	}

	/**
	 * 
	 * @param elev 
	 * @return 
	 */
	public int adaugareAbsenta(Elev elev) {
	}

	/**
	 * 
	 * @param numeElev 
	 * @return 
	 */
	public boolean existaElev(String numeElev) {
	}

	/**
	 * 
	 */
	public void topAbsente() {
	}

	/**
	 * 
	 */
	public void topEleviNote() {
	}
};
