// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

/************************************************************/
/**
 * 
 */
public enum Materie {

	Istorie,
	Matematica,
	Biologie,
	Informatica,
	Chimie,
	Geografie,
	Educatie_Fizica,
	Fizica,
	Desen;
};
