// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import tema1reloaded.Elev;
import tema1reloaded.Persoana;

/************************************************************/
/**
 * 
 */
public class Parinte extends Persoana {
	/**
	 * 
	 */
	private Elev[] copiiElevi;

	/**
	 * 
	 */
	public void verificareNote() {
	}

	/**
	 * 
	 * @param copil 
	 */
	public void adaugareCopil(Elev copil) {
	}

	/**
	 * 
	 * @param copil 
	 */
	public void stergereCopil(Elev copil) {
	}

	/**
	 * 
	 */
	public void getNume() {
	}

	/**
	 * 
	 */
	public void getTelefon() {
	}

	/**
	 * 
	 */
	public void getCNP() {
	}
};
