// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

/************************************************************/
/**
 * 
 */
public class Persoana {
	/**
	 * 
	 */
	protected String nume;
	/**
	 * 
	 */
	protected String CNP;
	/**
	 * 
	 */
	protected long telefon;
	
	public Persoana(String nume, String CNP, long telefon) {
		this.nume = nume;
		this.CNP = CNP;
		this.telefon = telefon;
	}
	
	public void afisare() {
		System.out.println("Nume: " + this.nume);
		System.out.println("CNP: " + this.CNP);
		System.out.println("Telefon: " + this.telefon);
	}

	
};
