// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

/************************************************************/
/**
 * 
 */
public class Persoana {
	/**
	 * 
	 */
	protected String nume;
	/**
	 * 
	 */
	protected String CNP;
	/**
	 * 
	 */
	protected long telefon;

	/**
	 * 
	 */
	public void getNume() {
	}

	/**
	 * 
	 */
	public void getCNP() {
	}

	/**
	 * 
	 */
	public void getTelefon() {
	}
};
