// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import tema1reloaded.Elev;
import tema1reloaded.Grupa;
import tema1reloaded.Materie;
import tema1reloaded.Persoana;

/************************************************************/
/**
 * 
 */
public class Profesor extends Persoana {
	/**
	 * 
	 */
	private boolean esteDiriginte;
	/**
	 * 
	 */
	private Grupa diriginteLaGrupa;
	/**
	 * 
	 */
	private Materie materiePredata;
	/**
	 * 
	 */
	private Grupa[] grupeUndePreda;
	/**
	 * 
	 */
	public Elev[] elev;

	/**
	 * 
	 * @param elev 
	 * @param nota 
	 * @return 
	 */
	public short notareElev(Elev elev, short nota) {
	}

	/**
	 * 
	 * @param elev 
	 * @return 
	 */
	public int adaugareAbsenta(Elev elev) {
	}

	/**
	 * 
	 * @param elev 
	 * @return 
	 */
	public int motivareAbsenta(Elev elev) {
	}

	/**
	 * 
	 */
	public void notificareSedinta() {
	}

	/**
	 * 
	 */
	public void getNume() {
	}

	/**
	 * 
	 */
	public void getTelefon() {
	}

	/**
	 * 
	 */
	public void getCNP() {
	}
};
