// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package tema1reloaded;

import java.util.ArrayList;

/************************************************************/
/**
 * 
 */
public class Profesor extends Persoana {

	private boolean esteDiriginte;
	private String diriginteLaGrupa;
	private Materie materiePredata;
	private ArrayList<Grupa> grupeUndePreda;
	
	
	public Profesor(String nume, String CNP, long telefon, boolean esteDiriginte, String diriginteLaGrupa,
			Materie materiePredata) {
		super(nume, CNP, telefon);
		this.esteDiriginte = esteDiriginte;
		
		if(esteDiriginte)
			this.diriginteLaGrupa = diriginteLaGrupa;
		
		this.materiePredata = materiePredata;
		this.grupeUndePreda = new ArrayList<Grupa>();
	}
	
	public void adaugaGrupaLaCarePreda(Grupa grupa) {
		if(!predaLaGrupa(grupa))
			grupeUndePreda.add(grupa);
		else
			System.out.println("Grupa a fost deja adaugata");
	}
	
	public void notareElev(Elev elev, int nota) {
		for(Grupa grupa : grupeUndePreda) 
			if(grupa.existaElev(elev.nume)) {
				grupa.adaugareNota(elev, this.materiePredata, nota);
			}
	}
	
	public void adaugareAbsenta(Elev elev) {
		for(Grupa grupa : grupeUndePreda) 
			if(grupa.existaElev(elev.nume)) {
				grupa.adaugareAbsenta(elev,1);
			}
	}
	
	public void motivareAbsenta(Elev elev) {
		if(this.esteDiriginte) {
			for(Grupa grupa : grupeUndePreda) 
				if(grupa.existaElev(elev.nume)) {
					if(grupa.getNumeGrupa().equals(this.diriginteLaGrupa))
						grupa.motivareAbsenta(elev);
				}
		}
		else
			System.out.println("Mars ca nu esti diriginte");
	}

	public void notificareSedinta() {
		if(this.esteDiriginte)
			System.out.println("Astazi ora 18.00, grupa " + this.diriginteLaGrupa + ", sedinta sau va tai!");
		else 
			System.out.println("Nu esti diriginte");
	}

	public boolean isDiriginte() {
		return this.esteDiriginte;
	}
	
	public boolean predaLaGrupa(Grupa g) {
		return grupeUndePreda.contains(g);
	}
};
